// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    CarbonHelp: typeof import('~icons/carbon/help')['default']
    CarbonLaunch: typeof import('~icons/carbon/launch')['default']
    CarbonLaunchFilled: typeof import('~icons/carbon/launch-filled')['default']
    CarbonPhone: typeof import('~icons/carbon/phone')['default']
    CarbonPhoneFilled: typeof import('~icons/carbon/phone-filled')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NoticeCorona: typeof import('./src/components/NoticeCorona.vue')['default']
    NoticeHoliday: typeof import('./src/components/NoticeHoliday.vue')['default']
    NoticeJob: typeof import('./src/components/NoticeJob.vue')['default']
  }
}

export { }
