// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BaseLayout: typeof import('./src/layouts/base.vue')['default']
    CarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    CarbonHelp: typeof import('~icons/carbon/help')['default']
    CarbonPhoneFilled: typeof import('~icons/carbon/phone-filled')['default']
    Head: typeof import('@vueuse/head')['Head']
    MetaTags: typeof import('./src/components/MetaTags.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NoticeCorona: typeof import('./src/components/NoticeCorona.vue')['default']
    NoticeHoliday: typeof import('./src/components/NoticeHoliday.vue')['default']
    NoticeJob: typeof import('./src/components/NoticeJob.vue')['default']
  }
}

export { }
