// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    CarbonDirectionLoopLeft: typeof import('~icons/carbon/direction-loop-left')['default']
    CarbonDirectionLoopLeftFilled: typeof import('~icons/carbon/direction-loop-left-filled')['default']
    CarbonHelp: typeof import('~icons/carbon/help')['default']
    CarbonPhoneFilled: typeof import('~icons/carbon/phone-filled')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    NavBack: typeof import('./components/NavBack.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
  }
}

export { }
