// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    CarbonHelp: typeof import('~icons/carbon/help')['default']
    CarbonPhoneFilled: typeof import('~icons/carbon/phone-filled')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NoticeCorona: typeof import('./components/NoticeCorona.vue')['default']
    NoticeHoliday: typeof import('./components/NoticeHoliday.vue')['default']
    NoticeJob: typeof import('./components/NoticeJob.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
  }
}

export { }
